version: "3.3"
services:
  elasticsearch:
    image: elasticsearch:7.14.0
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    volumes:
      - type: bind
        source: ./es_data
        target: /usr/share/elasticsearch/data

      - type: bind
        source: ./elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - target: 9200
        published: 9200
    networks:
      - network1

volumes:
  es_data:
    driver: local

networks:
  network1:
